name = "FileType"
uuid = "b58e86d0-4a47-4fce-a54d-8006a143ed90"
authors = ["princekrroshan01 <princekrroshan01@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
BenchmarkTools = "1"